# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 3.7.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages: ["commit-msg"]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0

  # --- Strip output from .ipynb files ---
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # --- Linters ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix-only]
        types_or: [python, pyi, jupyter]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [commit]
        additional_dependencies:
          - "prettier@3.1.0"
          - "prettier-plugin-toml@1.0.0"
          - "prettier-plugin-ini@1.1.0"
          - "prettier-plugin-properties@0.3.0"
          - "prettier-plugin-sql@0.15.1"
          - "@prettier/plugin-xml@3.2.1"
          - "prettier-plugin-sh@0.13.1"
