# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

body:
  - type: input
    id: suggestion
    attributes:
      label: Suggestion
      description: "How might we make this project better?"
      placeholder: "Adding more features would be great."
    validations:
      required: true
